development:
  adapter: mysql2
  encoding: utf8
  database: brain_development
  pool: 5
  username: root
  password: 
  host: localhost
  
test:
  adapter: mysql2
  encoding: utf8
  database: brain_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: brain_production
  pool: 5
  username: root
  password: 
  host: localhost